import type { Product, ProductCategory, Review } from "@/types";

export const categories: ProductCategory[] = [
  { id: "cat-1", name: "Ceramics", slug: "ceramics", description: "Hand-thrown stoneware and porcelain" },
  { id: "cat-2", name: "Textiles", slug: "textiles", description: "Woven and printed fabrics" },
  { id: "cat-3", name: "Glassware", slug: "glassware", description: "Blown and cast glass objects" },
  { id: "cat-4", name: "Jewelry", slug: "jewelry", description: "Handcrafted metal and stone jewelry" },
  { id: "cat-5", name: "Woodwork", slug: "woodwork", description: "Turned and carved wood pieces" },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Oribe Stoneware Vase",
    slug: "oribe-stoneware-vase",
    description:
      "Inspired by Japanese Oribe ware, this hand-thrown vase features a dramatic copper-green glaze with deliberate drips and pooling. Each piece is unique — the glaze reacts differently in every firing. Food-safe, dishwasher-safe, made in our Portland studio.",
    shortDescription: "Hand-thrown stoneware with copper-green Oribe glaze.",
    price: 148,
    currency: "USD",
    images: [
      { id: "img-1a", url: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80", alt: "Oribe vase front", isPrimary: true },
      { id: "img-1b", url: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80", alt: "Oribe vase detail" },
    ],
    category: categories[0],
    tags: ["vase", "japanese", "stoneware", "green"],
    rating: 4.9,
    reviewCount: 34,
    inStock: true,
    stockCount: 6,
    sku: "CER-OV-001",
    variants: [
      {
        label: "Size",
        options: [
          { id: "v-sm", name: "Size", value: "Small (6in)", inStock: true },
          { id: "v-md", name: "Size", value: "Medium (9in)", inStock: true, priceModifier: 30 },
          { id: "v-lg", name: "Size", value: "Large (12in)", inStock: false, priceModifier: 70 },
        ],
      },
    ],
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2024-11-01",
  },
  {
    id: "prod-2",
    name: "Indigo Block-Print Throw",
    slug: "indigo-block-print-throw",
    description:
      "Hand block-printed in Rajasthan using natural indigo dye on 100% organic cotton. The dabu mud-resist technique creates an irregular, living pattern that deepens with washing. 50 × 70 inches.",
    shortDescription: "Natural indigo dabu block-print cotton throw, 50×70in.",
    price: 215,
    compareAtPrice: 265,
    currency: "USD",
    images: [
      { id: "img-2a", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", alt: "Indigo throw folded", isPrimary: true },
    ],
    category: categories[1],
    tags: ["throw", "indigo", "block-print", "cotton", "sale"],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    stockCount: 14,
    sku: "TEX-IBT-001",
    isFeatured: true,
    createdAt: "2024-09-15",
  },
  {
    id: "prod-3",
    name: "Smoke-Pulled Wine Glasses",
    slug: "smoke-pulled-wine-glasses",
    description:
      "Mouth-blown borosilicate glass with a smoke-grey gradient pulled from the base. Sold as a set of two. The slight wobble and non-uniform rim are intentional marks of the hand.",
    shortDescription: "Mouth-blown borosilicate wine glasses with smoke gradient, set of 2.",
    price: 88,
    currency: "USD",
    images: [
      { id: "img-3a", url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80", alt: "Smoke wine glasses", isPrimary: true },
    ],
    category: categories[2],
    tags: ["glass", "wine", "smoke", "handblown"],
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    stockCount: 22,
    sku: "GLS-SWG-002",
    isNew: true,
    createdAt: "2025-01-10",
  },
  {
    id: "prod-4",
    name: "Forged Bronze Ring",
    slug: "forged-bronze-ring",
    description:
      "Hand-forged from solid bronze bar stock. The surface is left slightly rough from the hammer, then patinated with a liver-of-sulfur solution for an antique finish. Specify your ring size at checkout.",
    shortDescription: "Hand-forged solid bronze ring with hammer texture and patina.",
    price: 72,
    currency: "USD",
    images: [
      { id: "img-4a", url: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80", alt: "Bronze ring on hand", isPrimary: true },
    ],
    category: categories[3],
    tags: ["ring", "bronze", "forged", "jewelry"],
    rating: 4.6,
    reviewCount: 28,
    inStock: true,
    stockCount: 8,
    sku: "JEW-FBR-001",
    variants: [
      {
        label: "Ring Size",
        options: [
          { id: "rs-5", name: "Ring Size", value: "5", inStock: true },
          { id: "rs-6", name: "Ring Size", value: "6", inStock: true },
          { id: "rs-7", name: "Ring Size", value: "7", inStock: true },
          { id: "rs-8", name: "Ring Size", value: "8", inStock: false },
          { id: "rs-9", name: "Ring Size", value: "9", inStock: true },
        ],
      },
    ],
    isNew: true,
    createdAt: "2025-01-20",
  },
  {
    id: "prod-5",
    name: "Walnut Tasting Board",
    slug: "walnut-tasting-board",
    description:
      "Turned from a single slab of American black walnut. The live edge is preserved on one side; the opposite side is cut clean. Finished with food-grade beeswax and walnut oil. Approximately 14 × 10 inches.",
    shortDescription: "American black walnut live-edge charcuterie board, ~14×10in.",
    price: 165,
    currency: "USD",
    images: [
      { id: "img-5a", url: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&q=80", alt: "Walnut board with food", isPrimary: true },
    ],
    category: categories[4],
    tags: ["wood", "walnut", "board", "kitchen", "food-safe"],
    rating: 5.0,
    reviewCount: 17,
    inStock: true,
    stockCount: 4,
    sku: "WD-WTB-001",
    isFeatured: true,
    isBestSeller: true,
    createdAt: "2024-10-05",
  },
  {
    id: "prod-6",
    name: "Terra Cotta Planter Set",
    slug: "terra-cotta-planter-set",
    description:
      "Three hand-pinched terra cotta planters in graduated sizes. Drainage holes included. The unglazed exterior allows roots to breathe and develops a beautiful patina over time.",
    shortDescription: "Set of 3 hand-pinched terra cotta planters with drainage holes.",
    price: 95,
    currency: "USD",
    images: [
      { id: "img-6a", url: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800&q=80", alt: "Terra cotta planters", isPrimary: true },
    ],
    category: categories[0],
    tags: ["planter", "terra cotta", "garden", "set"],
    rating: 4.5,
    reviewCount: 63,
    inStock: true,
    stockCount: 11,
    sku: "CER-TCP-003",
    createdAt: "2024-08-20",
  },
  {
    id: "prod-7",
    name: "Hand-Knotted Wool Runner",
    slug: "hand-knotted-wool-runner",
    description:
      "Woven by artisans in Oaxaca on a traditional backstrap loom. Natural undyed wool in cream and charcoal. 2.5 × 8 feet. Each runner takes approximately three weeks to complete.",
    shortDescription: "Backstrap-loom woven wool runner in natural undyed cream and charcoal, 2.5×8ft.",
    price: 345,
    currency: "USD",
    images: [
      { id: "img-7a", url: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&q=80", alt: "Wool runner on floor", isPrimary: true },
    ],
    category: categories[1],
    tags: ["rug", "wool", "runner", "woven", "oaxaca"],
    rating: 4.9,
    reviewCount: 11,
    inStock: false,
    stockCount: 0,
    sku: "TEX-HWR-002",
    createdAt: "2024-07-01",
  },
  {
    id: "prod-8",
    name: "Amber Bud Vase",
    slug: "amber-bud-vase",
    description:
      "Mouth-blown amber glass bud vase with an elongated neck. Made in a small glass studio in Vermont. Holds a single stem beautifully. Approximately 8 inches tall.",
    shortDescription: "Mouth-blown amber glass bud vase, ~8in tall.",
    price: 58,
    currency: "USD",
    images: [
      { id: "img-8a", url: "https://images.unsplash.com/photo-1487700160041-babef9c3cb55?w=800&q=80", alt: "Amber bud vase with flower", isPrimary: true },
    ],
    category: categories[2],
    tags: ["vase", "amber", "glass", "bud vase"],
    rating: 4.7,
    reviewCount: 44,
    inStock: true,
    stockCount: 18,
    sku: "GLS-ABV-001",
    isBestSeller: true,
    createdAt: "2024-06-10",
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    userId: "user-1",
    userName: "Margot K.",
    rating: 5,
    title: "Absolutely stunning",
    body: "I've been looking for a vase like this for years. The glaze has this gorgeous depth — different colors in different light. It arrived so carefully packed, not a scratch.",
    verified: true,
    helpful: 12,
    createdAt: "2024-12-15",
  },
  {
    id: "rev-2",
    productId: "prod-1",
    userId: "user-2",
    userName: "Theo R.",
    rating: 5,
    title: "Better than the photos",
    body: "The photos are good but they don't fully capture how the glaze shifts between blue-green and copper depending on the light. Highly recommend the medium size.",
    verified: true,
    helpful: 8,
    createdAt: "2025-01-03",
  },
];
